### ISSUE TITLE
Slack no longer loads with build 12.20

### ISSUE THREAD

**Issue by neilio** [getstation/station-canary#1]
Works on 12.19, but under 12.20 the loading screen spins and spins but Slack never fully loads.

**Comment by neilio** [comment]
Seems to be a migration issue - I blew away the app support folder and Slack started working again.

**Comment by neilio** [comment]
Restarted the app and the issue came back. build 21 has the same problem - Slack will not load at all.

**Comment by alexstrat** [comment]
@neilio 
- can you open the developer tools of the Slack app: View > Developers > Toggle Page Developer Tools and see if there is errors in your console
- are you using Mixmax in Gmail (we thought it was linked)

**Comment by neilio** [comment]
This is fixed in 21.
