### ISSUE TITLE
Google Calendar freezes

### ISSUE THREAD

**Issue by neilio** [getstation/station-canary#4]
I keep running into an issue where Google Calendar stops accepting clicks or scrolling events, and the only way to get it to work is to reload from the View / Reload this Page menu item. This is on 0.17.20.

**Comment by neilio** [comment]
Seems to be fixed? Will close for now.

**Comment by neilio** [comment]
Still an issue with 0.17.21. I can't reliably reproduce the issue but it happens very frequently.

**Comment by alexstrat** [comment]
@neilio Thanks :)! Would you mind testing with Canary 0.17.22 and let us know if you still see the issue! Thanks!

**Comment by neilio** [comment]
@alexstrat Sadly I still see the issue. Can I send you logs or anything else that might be helpful?

**Comment by alexstrat** [comment]
@neilio do you have a way to reproduce the issue one way or an other?

**Comment by alexstrat** [comment]
And btw you are sure you are on the latest version?

**Comment by neilio** [comment]
I'm on 0.17.22. I've been trying to reproduce the problem but haven't found a way yet. Will keep trying!

**Comment by alexstrat** [comment]
@neilio can you keep the Calendar dev tool open and take a screenshot of the dev tool when it happens. esp. the network tab.

**Comment by neilio** [comment]
![image](https://user-images.githubusercontent.com/1400/47507149-9d654880-d83f-11e8-9e48-5acd807eae88.png)
Just managed to get it to reproduce now - I think (?) it's connected to notifications as I had just gotten a calendar notification, switched to the app, and it was frozen.

**Comment by neilio** [comment]
Yup, it seems to be related to calendar notifications - just happened again.

**Comment by alexstrat** [comment]
Definitely! We were able to reproduce! Will be easier now! Thanks! We keep you posted

**Comment by neilio** [comment]
Merci!

**Comment by neilio** [comment]
Seems fixed in 0.17.24. Thanks!
