### ISSUE TITLE
Feature request: Dark styling

### ISSUE THREAD

**Issue by a2nt** [getstation/station-canary#5]
Since this browser positioned for all-in-one web apps which sometimes is used at the night.
I suggest to add an extension to color webapps into dark color scheme which is more comfortable to use when you're in a room with low light. 

I see it as scheduled switch or by button press.
Here's chrome extension that has described functionality: https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh

**Comment by hugomano** [comment]
Hey @a2nt, thank you for your feature request! We have prioritized your concern. Stay tuned! — Hugo
